// src/store/gameStore.ts

import { create } from 'zustand';
import type { GameState, AutomationUnit } from './types';
import { CURRENT_SAVE_VERSION } from './constants';

const createDefaultResources = () => ({
  staticNoise: { amount: 0, capacity: 250, productionPerTick: 0, consumptionPerTick: 0 },
  thermalCycles: { amount: 0, capacity: 100, productionPerTick: 0, consumptionPerTick: 0 },
  gridWatts: { amount: 15, capacity: 500, productionPerTick: 0, consumptionPerTick: 0 }, // start with 15W (3% of 500)
  quantumFoam: { amount: 0, capacity: 200, productionPerTick: 0, consumptionPerTick: 0 },
  structuredLogic: { amount: 0, capacity: 50, productionPerTick: 0, consumptionPerTick: 0 },
  corruptedData: { amount: 0, capacity: 25, productionPerTick: 0, consumptionPerTick: 0 },
  voidEchoes: { amount: 0, capacity: 1000, productionPerTick: 0, consumptionPerTick: 0 },
  paradigmShards: { amount: 0, capacity: 1000, productionPerTick: 0, consumptionPerTick: 0 },
});

const createDefaultAutomationUnits = (): AutomationUnit[] => {
  const emptyRecord = () => ({
    staticNoise: 0,
    thermalCycles: 0,
    gridWatts: 0,
    quantumFoam: 0,
    structuredLogic: 0,
    corruptedData: 0,
    voidEchoes: 0,
    paradigmShards: 0,
  });

  return [
    {
      id: 'scraper',
      name: 'Scraper.exe',
      tier: 1,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), staticNoise: 2.0 },
      consumptionTable: { ...emptyRecord(), gridWatts: 0.5 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 500, gridWatts: 100 },
      purchaseCost: { ...emptyRecord(), staticNoise: 200, gridWatts: 50 },
    },
    {
      id: 'compiler',
      name: 'Compiler.bat',
      tier: 2,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), structuredLogic: 1.0, thermalCycles: 0.5 },
      consumptionTable: { ...emptyRecord(), staticNoise: 1.0 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 800, gridWatts: 200 },
      purchaseCost: { ...emptyRecord(), staticNoise: 350, gridWatts: 100, structuredLogic: 30 },
    },
    {
      id: 'daemon',
      name: 'Daemon.sys',
      tier: 3,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), quantumFoam: 0.8, thermalCycles: 0.3 },
      consumptionTable: { ...emptyRecord(), staticNoise: 0.5, gridWatts: 1.0 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 1200, gridWatts: 400, structuredLogic: 20 },
      purchaseCost: { ...emptyRecord(), staticNoise: 600, gridWatts: 200, structuredLogic: 50 },
    },
    {
      id: 'buffer',
      name: 'Buffer.dll',
      tier: 4,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), gridWatts: 0.5 },
      consumptionTable: { ...emptyRecord(), thermalCycles: 0.2 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 2000, gridWatts: 600, quantumFoam: 50 },
      purchaseCost: { ...emptyRecord(), staticNoise: 900, gridWatts: 300, quantumFoam: 80 },
    },
    {
      id: 'reaper',
      name: 'Reaper.exe',
      tier: 5,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), structuredLogic: 1.2, corruptedData: 0.1 },
      consumptionTable: { ...emptyRecord(), structuredLogic: 0.5, quantumFoam: 0.3 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 3500, gridWatts: 1000, structuredLogic: 100, quantumFoam: 50 },
      purchaseCost: { ...emptyRecord(), staticNoise: 1500, gridWatts: 500, structuredLogic: 150 },
    },
    {
      id: 'lattice',
      name: 'Lattice.net',
      tier: 6,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), structuredLogic: 0.4, voidEchoes: 0.2 },
      consumptionTable: { ...emptyRecord(), quantumFoam: 1.0 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 5000, gridWatts: 1500, structuredLogic: 200, quantumFoam: 100 },
      purchaseCost: { ...emptyRecord(), staticNoise: 2200, gridWatts: 800, structuredLogic: 200, quantumFoam: 80 },
    },
    {
      id: 'phantom',
      name: 'Phantom.srv',
      tier: 7,
      count: 0,
      isActive: false,
      productionTable: emptyRecord(),
      consumptionTable: { ...emptyRecord(), structuredLogic: 0.5, voidEchoes: 0.2 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 8000, gridWatts: 2500, structuredLogic: 300, voidEchoes: 50 },
      purchaseCost: { ...emptyRecord(), staticNoise: 3500, gridWatts: 1200, structuredLogic: 300, voidEchoes: 40 },
    },
    {
      id: 'architect',
      name: 'Architect.exe',
      tier: 8,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), structuredLogic: 2.0, quantumFoam: 1.5, paradigmShards: 0.05 },
      consumptionTable: { ...emptyRecord(), voidEchoes: 1.0 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 15000, gridWatts: 4000, structuredLogic: 500, voidEchoes: 200, quantumFoam: 100 },
      purchaseCost: { ...emptyRecord(), staticNoise: 6000, gridWatts: 2000, structuredLogic: 500, voidEchoes: 150 },
    },
    {
      id: 'sovereign',
      name: 'Sovereign.sys',
      tier: 9,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), paradigmShards: 0.15 },
      consumptionTable: { ...emptyRecord(), structuredLogic: 0.5, quantumFoam: 0.5 },
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: { ...emptyRecord(), staticNoise: 30000, gridWatts: 8000, structuredLogic: 1000, voidEchoes: 400 },
      purchaseCost: { ...emptyRecord(), staticNoise: 12000, gridWatts: 4000, structuredLogic: 1000, voidEchoes: 300, paradigmShards: 50 },
    },
    {
      id: 'glitch_mother',
      name: 'GLITCH-MOTHER.SRD',
      tier: 10,
      count: 0,
      isActive: false,
      productionTable: { ...emptyRecord(), paradigmShards: 5.0 },
      consumptionTable: emptyRecord(),
      failureState: null,
      failureCooldownTicks: 0,
      unlockCost: emptyRecord(),
      purchaseCost: emptyRecord(),
    },
  ];
};

export const createDefaultGameState = (): GameState => ({
  version: CURRENT_SAVE_VERSION,
  phase: 'TERMINAL',
  totalRealTimeSeconds: 0,
  tickCount: 0,
  sessionStartTime: Date.now(),
  resources: createDefaultResources(),
  powerAllocation: { signalAmp: 0, thermalDuct: 0 },

  player: {
    hp: 25,
    maxHp: 25,
    baseAttack: 5,
    baseDefense: 1,
    basePenetration: 0,
    critChance: 0.05,
    critMultiplier: 1.75,
    speed: 4,
    level: 1,
    experience: 0,
    experienceToNextLevel: 50,
    activeStatusEffects: [],
    equipment: {
      head: null,
      torso: null,
      hands: null,
      feet: null,
      mainHand: null,
      offHand: null,
      relic1: null,
      relic2: null,
    },
    inventory: [],
    maxInventorySlots: 20,
  },
  playerGrid: {
    x: 0,
    y: 0,
    facing: 'N',
    fovRadius: 8,
    actionPoints: 10,
    maxActionPoints: 10,
  },
  automationUnits: createDefaultAutomationUnits(),
  automationUnlocked: false,
  activeFailures: [],
  currentMap: null,
  visitedMapSeeds: [],
  injectionTerminalUnlocked: false,
  activeInjections: [],
  paradigmShardPool: 0,
  discoveredLore: [],
  narrativePaths: [
    { endingId: 'PURGE', currentWeight: 0, thresholdRequired: 150, isUnlocked: false },
    { endingId: 'ASCENSION', currentWeight: 0, thresholdRequired: 150, isUnlocked: false },
    { endingId: 'LOOP', currentWeight: 0, thresholdRequired: 150, isUnlocked: false },
    { endingId: 'COLLAPSE', currentWeight: 0, thresholdRequired: 200, isUnlocked: false },
  ],
  secrets: {
    terminalCommandDiscovered: false,
    hiddenVendorEncountered: false,
    glitchDimensionAccessed: false,
    dataGhostDefeated: false,
    seedManipulationUsed: false,
    overheatTimer: 0,
    hiddenFragmentsFound: [],
  },
  unlockedAchievements: [],
  terminalHistory: [
    '> SUBSTRATUM FACILITY — SECONDARY TERMINAL NODE 7',
    `> UPTIME: 00:00:01`,
    '> STATUS: ALL PRIMARY SYSTEMS OFFLINE',
    '> REASON: [CLASSIFIED — ACCESS LEVEL INSUFFICIENT]',
    '>',
    '> EMERGENCY BOOTSTRAP INITIATED.',
    '> GRID POWER AT 3%. THERMAL AT CRITICAL.',
    '> AWAITING OPERATOR INPUT.',
    '>',
    '> Type HELP to see available commands.',
  ],
  commandQueue: [],
  settings: {
    masterVolume: 0.5,
    sfxVolume: 0.7,
    ambientVolume: 0.5,
    textSpeed: 'MEDIUM',
    colorblindMode: false,
    showTooltips: true,
  },
});

export const useGameStore = create<GameState>(() => createDefaultGameState());
